ontology:
  path: resources/pizza.owl
  language: es

annotators:
  - name: ontology
  # - name: stanza-ner
  - name: temporal
  - name: regex
    layer: pizza-order
    source: resources/pizza_regex.yml
    color: "#ffe0b2"

resolver:
  enabled: true
  strategy: longest_match

metrics:

  tfidf:
    enabled: true
    layer: ontology

  extended_tfidf:
    enabled: true
    layer: ontology

    # ancestors | all
    direction: ancestors

    # profundidad máxima en la ontología
    max_distance: 5

    decay:
      # exponential | inverse | none
      type: exponential

      # λ
      value: 0.5